[pytest]
minversion = 8.0
DJANGO_SETTINGS_MODULE = settings.test
testpaths = app
norecursedirs =
    __pycache__
    migrations
python_files =
    test_*.py
    tests.py
addopts =
    -v -p no:warnings
    --durations=0
    --migrations
markers =
    code: test that checks if code structure, syntax and linting are correct.
