# Generated by Django 6.0.4 on 2026-04-21 19:17

import app.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonce",
            name="value",
            field=app.utils.fields.CharField(max_length=128, unique=True),
        ),
    ]
