# Generated by Django 6.0.4 on 2026-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="key",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
