[program:permyt_mcp_app]
command=/var/deployments/mcp/env/bin/uvicorn settings.asgi:application --host 127.0.0.1 --port 9020 --workers 2
directory=/var/deployments/mcp
stderr_logfile=/var/deployments/mcp/logs/app.stderr.log
stdout_logfile=/var/deployments/mcp/logs/app.stdout.log
autostart=true
autorestart=true
user=ubuntu
environment=HOME="/home/ubuntu",USER="ubuntu"
numprocs=1
process_name=%(program_name)s_%(process_num)s
