# Generated by Django 6.0.4 on 2026-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthauthorizationcode",
            name="expires_at",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="oauthauthorizationsession",
            name="expires_at",
            field=models.IntegerField(),
        ),
    ]
